package(default_visibility = ["//tensorflow_estimator:internal"])

licenses(["notice"])  # Apache 2.0

load("//tensorflow_estimator/python/estimator/api:api_gen.bzl", "gen_api_init_files")

gen_api_init_files(
    name = "estimator_python_api_gen",
    api_version = 1,
)
