# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Utility methods to create simple input_fns.
"""

from __future__ import print_function

from tensorflow_estimator.python.estimator.inputs.inputs import numpy_input_fn
from tensorflow_estimator.python.estimator.inputs.inputs import pandas_input_fn

del print_function
