# Description: Tensorflow Estimator.

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

package_group(
    name = "internal",
    packages = [
        "//tensorflow_estimator/...",
    ],
)
